const UserTypes = {
  CLEAR_USER_STATE: 'CLEAR_USER_STATE',
  CLEAR_CREATE_USER_STATE: 'CLEAR_CREATE_USER_STATE',
  CLEAR_CHANGE_PASSWORD_STATE: 'CLEAR_CHANGE_PASSWORD_STATE',
  CLEAR_UPDATE_CURRENT_USER_STATE: 'CLEAR_UPDATE_CURRENT_USER_STATE',
  CLEAR_UPDATE_USER_INFO_STATE: 'CLEAR_UPDATE_USER_INFO_STATE',
  CLEAR_DELETE_USER_STATE: 'CLEAR_DELETE_USER_STATE',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_WITH_SOCIAL: 'LOGIN_WITH_SOCIAL',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  GET_USER_LIST: 'GET_USER_LIST',
  GET_USER_LIST_SUCCESS: 'GET_USER_LIST_SUCCESS',
  GET_USER_LIST_FAILURE: 'GET_USER_LIST_FAILURE',

  GET_USERNAME_LIST: 'GET_USERNAME_LIST',
  GET_USERNAME_LIST_SUCCESS: 'GET_USERNAME_LIST_SUCCESS',
  GET_USERNAME_LIST_FAILURE: 'GET_USERNAME_LIST_FAILURE',

  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',

  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAILURE: 'UPDATE_USER_INFO_FAILURE',

  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  UPDATE_CURRENT_USER_SUCCESS: 'UPDATE_CURRENT_USER_SUCCESS',
  UPDATE_CURRENT_USER_FAILURE: 'UPDATE_CURRENT_USER_FAILURE',

  UPDATE_CURRENT_USER_ON_AUTHENTICATE: 'UPDATE_CURRENT_USER_ON_AUTHENTICATE',
  UPDATE_CURRENT_USER_ON_AUTHENTICATE_SUCCESS: 'UPDATE_CURRENT_USER_ON_AUTHENTICATE_SUCCESS',
  UPDATE_CURRENT_USER_ON_AUTHENTICATE_FAILURE: 'UPDATE_CURRENT_USER_ON_AUTHENTICATE_FAILURE',

  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  SEND_VERIFY_EMAIL: 'SEND_VERIFY_EMAIL',
  SEND_VERIFY_EMAIL_SUCCESS: 'SEND_VERIFY_EMAIL_SUCCESS',
  SEND_VERIFY_EMAIL_FAILURE: 'SEND_VERIFY_EMAIL_FAILURE',

  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',

  SEND_RESET_PASSWORD_EMAIL: 'SEND_RESET_PASSWORD_EMAIL',
  SEND_RESET_PASSWORD_EMAIL_SUCCESS: 'SEND_RESET_PASSWORD_EMAIL_SUCCESS',
  SEND_RESET_PASSWORD_EMAIL_FAILURE: 'SEND_RESET_PASSWORD_EMAIL_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  LOGOUT: 'LOGOUT',
}

export default UserTypes
