const TokenTypes = {
  CLEAR_TOKEN_STATE: 'CLEAR_TOKEN_STATE',

  GET_USER_TOKENS: 'GET_USER_TOKENS',
  GET_USER_TOKENS_SUCCESS: 'GET_USER_TOKENS_SUCCESS',
  GET_USER_TOKENS_FAILURE: 'GET_USER_TOKENS_FAILURE',

  GET_PROJECT_TOKENS: 'GET_PROJECT_TOKENS',
  GET_PROJECT_TOKENS_SUCCESS: 'GET_PROJECT_TOKENS_SUCCESS',
  GET_PROJECT_TOKENS_FAILURE: 'GET_PROJECT_TOKENS_FAILURE',

  GET_TOKEN_TYPES: 'GET_TOKEN_TYPES',
  GET_TOKEN_TYPES_SUCCESS: 'GET_TOKEN_TYPES_SUCCESS',
  GET_TOKEN_TYPES_FAILURE: 'GET_TOKEN_TYPES_FAILURE',

  GET_FREE_TOKEN: 'GET_FREE_TOKEN',
  GET_FREE_TOKEN_SUCCESS: 'GET_FREE_TOKEN_SUCCESS',
  GET_FREE_TOKEN_FAILURE: 'GET_FREE_TOKEN_FAILURE',
}

export default TokenTypes
