const TokenTypes = {
  CLEAR_TOKEN_STATE: 'CLEAR_TOKEN_STATE',
  GET_TOKENS: 'GET_TOKENS',
  GET_TOKENS_SUCCESS: 'GET_TOKENS_SUCCESS',
  GET_TOKENS_FAILURE: 'GET_TOKENS_FAILURE',
}

export default TokenTypes
