const TokenTypes = {
  CLEAR_TOKEN_STATE: 'CLEAR_TOKEN_STATE',
  GET_TOKENS: 'GET_TOKENS',
  GET_TOKENS_SUCCESS: 'GET_TOKENS_SUCCESS',
  GET_TOKENS_FAILURE: 'GET_TOKENS_FAILURE',
  GET_TOKEN_TYPES: 'GET_TOKEN_TYPES',
  GET_TOKEN_TYPES_SUCCESS: 'GET_TOKEN_TYPES_SUCCESS',
  GET_TOKEN_TYPES_FAILURE: 'GET_TOKEN_TYPES_FAILURE',
}

export default TokenTypes
