const MonitorTypes = {
  CLEAR_MONITOR_STATE: 'CLEAR_MONITOR_STATE',

  GET_MONITORS: 'GET_MONITORS',
  GET_MONITORS_SUCCESS: 'GET_MONITORS_SUCCESS',
  GET_MONITORS_FAILURE: 'GET_MONITORS_FAILURE',
}

export default MonitorTypes
