FROM bitnami/redis:latest
ENV ALLOW_EMPTY_PASSWORD=yes
# USE FOR REPLICA LATER
#ENV REDIS_REPLICATION_MODE=slave
#ENV REDIS_MASTER_HOST=redis-master
#ENV REDIS_MASTER_PORT_NUMBER=6379
#ENV REDIS_MASTER_PASSWORD=my_master_password
#ENV REDIS_PASSWORD=my_replica_password