const ProjectTypes = {
  CLEAR_PROJECT_STATE: 'CLEAR_PROJECT_STATE',

  GET_PROJECT_LIST: 'GET_PROJECT_LIST',
  GET_PROJECT_LIST_SUCCESS: 'GET_PROJECT_LIST_SUCCESS',
  GET_PROJECT_LIST_FAILURE: 'GET_PROJECT_LIST_FAILURE',

  GET_MY_PROJECT_LIST: 'GET_MY_PROJECT_LIST',
  GET_MY_PROJECT_LIST_SUCCESS: 'GET_MY_PROJECT_LIST_SUCCESS',
  GET_MY_PROJECT_LIST_FAILURE: 'GET_MY_PROJECT_LIST_FAILURE',

  GET_ACCEPTED_PROJECT_LIST: 'GET_ACCEPTED_PROJECT_LIST',
  GET_ACCEPTED_PROJECT_LIST_SUCCESS: 'GET_ACCEPTED_PROJECT_LIST_SUCCESS',
  GET_ACCEPTED_PROJECT_LIST_FAILURE: 'GET_ACCEPTED_PROJECT_LIST_FAILURE',

  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',

  GET_PROJECT_INFO: 'GET_PROJECT_INFO',
  GET_PROJECT_INFO_SUCCESS: 'GET_PROJECT_INFO_SUCCESS',
  GET_PROJECT_INFO_FAILURE: 'GET_PROJECT_INFO_FAILURE',

  UPDATE_PROJECT_INFO: 'UPDATE_PROJECT_INFO',
  UPDATE_PROJECT_INFO_SUCCESS: 'UPDATE_PROJECT_INFO_SUCCESS',
  UPDATE_PROJECT_INFO_FAILURE: 'UPDATE_PROJECT_INFO_FAILURE',

  DELETE_PROJECT: 'DELETE_PROJECT',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',
}

export default ProjectTypes
