const PermissionTypes = {
  CLEAR_PERMISSION_STATE: 'CLEAR_PERMISSION_STATE',
  CLEAR_ASSIGN_PERMISSION_STATE: 'CLEAR_ASSIGN_PERMISSION_STATE',
  CLEAR_REPLY_PERMISSION_ASSIGN_STATE: 'CLEAR_REPLY_PERMISSION_ASSIGN_STATE',
  CLEAR_UPDATE_PERMISSION_EXPIRATION_DATE_STATE: 'CLEAR_UPDATE_PERMISSION_EXPIRATION_DATE_STATE',
  CLEAR_DELETE_PERMISSION_FOR_ASSIGNEE_STATE: 'CLEAR_DELETE_PERMISSION_FOR_ASSIGNEE_STATE',

  ASSIGN_PERMISSION: 'ASSIGN_PERMISSION',
  ASSIGN_PERMISSION_SUCCESS: 'ASSIGN_PERMISSION_SUCCESS',
  ASSIGN_PERMISSION_FAILURE: 'ASSIGN_PERMISSION_FAILURE',

  REPLY_PERMISSION_ASSIGN: 'REPLY_PERMISSION_ASSIGN',
  REPLY_PERMISSION_ASSIGN_SUCCESS: 'REPLY_PERMISSION_ASSIGN_SUCCESS',
  REPLY_PERMISSION_ASSIGN_FAILURE: 'REPLY_PERMISSION_ASSIGN_FAILURE',

  FIND_PERMISSION_BY_EMAIL_TOKEN: 'FIND_PERMISSION_BY_EMAIL_TOKEN',
  FIND_PERMISSION_BY_EMAIL_TOKEN_SUCCESS: 'FIND_PERMISSION_BY_EMAIL_TOKEN_SUCCESS',
  FIND_PERMISSION_BY_EMAIL_TOKEN_FAILURE: 'FIND_PERMISSION_BY_EMAIL_TOKEN_FAILURE',

  UPDATE_PERMISSION_EXPIRATION_DATE: 'UPDATE_PERMISSION_EXPIRATION_DATE',
  UPDATE_PERMISSION_EXPIRATION_DATE_SUCCESS: 'UPDATE_PERMISSION_EXPIRATION_DATE_SUCCESS',
  UPDATE_PERMISSION_EXPIRATION_DATE_FAILURE: 'UPDATE_PERMISSION_EXPIRATION_DATE_FAILURE',

  DELETE_PERMISSION_FOR_ASSIGNEE: 'DELETE_PERMISSION_FOR_ASSIGNEE',
  DELETE_PERMISSION_FOR_ASSIGNEE_SUCCESS: 'DELETE_PERMISSION_FOR_ASSIGNEE_SUCCESS',
  DELETE_PERMISSION_FOR_ASSIGNEE_FAILURE: 'DELETE_PERMISSION_FOR_ASSIGNEE_FAILURE',
}

export default PermissionTypes
