const RequestTypes = {
  CLEAR_REQUEST_STATE: 'CLEAR_REQUEST_STATE',

  GET_REQUEST_LIST: 'GET_REQUEST_LIST',
  GET_REQUEST_LIST_SUCCESS: 'GET_REQUEST_LIST_SUCCESS',
  GET_REQUEST_LIST_FAILURE: 'GET_REQUEST_LIST_FAILURE',

  GET_REQUEST_LIST_BY_USERID: 'GET_REQUEST_LIST_BY_USERID',
  GET_REQUEST_LIST_BY_USERID_SUCCESS: 'GET_REQUEST_LIST_BY_USERID_SUCCESS',
  GET_REQUEST_LIST_BY_USERID_FAILURE: 'GET_REQUEST_LIST_BY_USERID_FAILURE',
}

export default RequestTypes
