const RequestTypes = {
  CLEAR_REQUEST_STATE: 'CLEAR_REQUEST_STATE',
  CLEAR_REQUEST_INFO: 'CLEAR_REQUEST_INFO',

  GET_REQUEST_INFO: 'GET_REQUEST_INFO',
  GET_REQUEST_INFO_SUCCESS: 'GET_REQUEST_INFO_SUCCESS',
  GET_REQUEST_INFO_FAILURE: 'GET_REQUEST_INFO_FAILURE',

  GET_REQUEST_LIST: 'GET_REQUEST_LIST',
  GET_REQUEST_LIST_SUCCESS: 'GET_REQUEST_LIST_SUCCESS',
  GET_REQUEST_LIST_FAILURE: 'GET_REQUEST_LIST_FAILURE',

  GET_REQUEST_LIST_BY_USERID: 'GET_REQUEST_LIST_BY_USERID',
  GET_REQUEST_LIST_BY_USERID_SUCCESS: 'GET_REQUEST_LIST_BY_USERID_SUCCESS',
  GET_REQUEST_LIST_BY_USERID_FAILURE: 'GET_REQUEST_LIST_BY_USERID_FAILURE',

  UPDATE_REQUEST_INFO: 'UPDATE_REQUEST_INFO',
  UPDATE_REQUEST_INFO_SUCCESS: 'UPDATE_REQUEST_INFO_SUCCESS',
  UPDATE_REQUEST_INFO_FAILURE: 'UPDATE_REQUEST_INFO_FAILURE',
}

export default RequestTypes
