const ReportTypes = {
  CLEAR_REPORT_STATE: 'CLEAR_REPORT_STATE',

  GET_PROJECT_STATISTICS: 'GET_PROJECT_STATISTICS',
  GET_PROJECT_STATISTICS_SUCCESS: 'GET_PROJECT_STATISTICS_SUCCESS',
  GET_PROJECT_STATISTICS_FAILURE: 'GET_PROJECT_STATISTICS_FAILURE',

  GET_TOKEN_STATISTICS: 'GET_TOKEN_STATISTICS',
  GET_TOKEN_STATISTICS_SUCCESS: 'GET_TOKEN_STATISTICS_SUCCESS',
  GET_TOKEN_STATISTICS_FAILURE: 'GET_TOKEN_STATISTICS_FAILURE',

  GET_TOKEN_TYPE_STATISTICS: 'GET_TOKEN_TYPE_STATISTICS',
  GET_TOKEN_TYPE_STATISTICS_SUCCESS: 'GET_TOKEN_TYPE_STATISTICS_SUCCESS',
  GET_TOKEN_TYPE_STATISTICS_FAILURE: 'GET_TOKEN_TYPE_STATISTICS_FAILURE',

  GET_USER_TOKEN_TYPE_STATISTICS: 'GET_USER_TOKEN_TYPE_STATISTICS',
  GET_USER_TOKEN_TYPE_STATISTICS_SUCCESS: 'GET_USER_TOKEN_TYPE_STATISTICS_SUCCESS',
  GET_USER_TOKEN_TYPE_STATISTICS_FAILURE: 'GET_USER_TOKEN_TYPE_STATISTICS_FAILURE',

  GET_USER_TOTAL_STATISTICS: 'GET_USER_TOTAL_STATISTICS',
  GET_USER_TOTAL_STATISTICS_SUCCESS: 'GET_USER_TOTAL_STATISTICS_SUCCESS',
  GET_USER_TOTAL_STATISTICS_FAILURE: 'GET_USER_TOTAL_STATISTICS_FAILURE',

  GET_ADMIN_TOTAL_STATISTICS: 'GET_ADMIN_TOTAL_STATISTICS',
  GET_ADMIN_TOTAL_STATISTICS_SUCCESS: 'GET_ADMIN_TOTAL_STATISTICS_SUCCESS',
  GET_ADMIN_TOTAL_STATISTICS_FAILURE: 'GET_ADMIN_TOTAL_STATISTICS_FAILURE',
}

export default ReportTypes
