const ReportTypes = {
  CLEAR_REPORT_STATE: 'CLEAR_REPORT_STATE',

  GET_STATISTICS_BY_ID: 'GET_STATISTICS_BY_ID',
  GET_STATISTICS_BY_ID_SUCCESS: 'GET_STATISTICS_BY_ID_SUCCESS',
  GET_STATISTICS_BY_ID_FAILURE: 'GET_STATISTICS_BY_ID_FAILURE',

  GET_USER_TOKEN_TYPE_STATISTICS: 'GET_USER_TOKEN_TYPE_STATISTICS',
  GET_USER_TOKEN_TYPE_STATISTICS_SUCCESS: 'GET_USER_TOKEN_TYPE_STATISTICS_SUCCESS',
  GET_USER_TOKEN_TYPE_STATISTICS_FAILURE: 'GET_USER_TOKEN_TYPE_STATISTICS_FAILURE',

  GET_USER_TOTAL_STATISTICS: 'GET_USER_TOTAL_STATISTICS',
  GET_USER_TOTAL_STATISTICS_SUCCESS: 'GET_USER_TOTAL_STATISTICS_SUCCESS',
  GET_USER_TOTAL_STATISTICS_FAILURE: 'GET_USER_TOTAL_STATISTICS_FAILURE',

  GET_ADMIN_TOTAL_STATISTICS: 'GET_ADMIN_TOTAL_STATISTICS',
  GET_ADMIN_TOTAL_STATISTICS_SUCCESS: 'GET_ADMIN_TOTAL_STATISTICS_SUCCESS',
  GET_ADMIN_TOTAL_STATISTICS_FAILURE: 'GET_ADMIN_TOTAL_STATISTICS_FAILURE',
}

export default ReportTypes
