const PermissionTypes = {
  CLEAR_PERMISSION_STATE: 'CLEAR_PERMISSION_STATE',

  ASSIGN_PERMISSION: 'ASSIGN_PERMISSION',
  ASSIGN_PERMISSION_SUCCESS: 'ASSIGN_PERMISSION_SUCCESS',
  ASSIGN_PERMISSION_FAILURE: 'ASSIGN_PERMISSION_FAILURE',
}

export default PermissionTypes
