const TransactionTypes = {
  CLEAR_TRANSACTION_STATE: 'CLEAR_TRANSACTION_STATE',

  GET_TRANSACTION_LIST: 'GET_TRANSACTION_LIST',
  GET_TRANSACTION_LIST_SUCCESS: 'GET_TRANSACTION_LIST_SUCCESS',
  GET_TRANSACTION_LIST_FAILURE: 'GET_TRANSACTION_LIST_FAILURE',

  CREATE_TRANSACTION: 'CREATE_CONTRACT',
}

export default TransactionTypes
