const OrderTypes = {
  CLEAR_ORDER_STATE: 'CLEAR_ORDER_STATE',

  GET_ORDER_LIST: 'GET_ORDER_LIST',
  GET_ORDER_LIST_SUCCESS: 'GET_ORDER_LIST_SUCCESS',
  GET_ORDER_LIST_FAILURE: 'GET_ORDER_LIST_FAILURE',

  CREATE_ORDER: 'CREATE_ORDER',
}

export default OrderTypes
