const OrderTypes = {
  CLEAR_ORDER_STATE: 'CLEAR_ORDER_STATE',
  CLEAR_CREATE_ORDER_STATE: 'CLEAR_CREATE_ORDER_STATE',

  GET_ORDER_LIST: 'GET_ORDER_LIST',
  GET_ORDER_LIST_SUCCESS: 'GET_ORDER_LIST_SUCCESS',
  GET_ORDER_LIST_FAILURE: 'GET_ORDER_LIST_FAILURE',

  GET_USER_ORDER_LIST: 'GET_USER_ORDER_LIST',
  GET_USER_ORDER_LIST_SUCCESS: 'GET_USER_ORDER_LIST_SUCCESS',
  GET_USER_ORDER_LIST_FAILURE: 'GET_USER_ORDER_LIST_FAILURE',

  GET_ORDER_INFO: 'GET_ORDER_INFO',
  GET_ORDER_INFO_SUCCESS: 'GET_ORDER_INFO_SUCCESS',
  GET_ORDER_INFO_FAILURE: 'GET_ORDER_INFO_FAILURE',

  CREATE_ORDER: 'CREATE_ORDER',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
}

export default OrderTypes
