const TaskTypes = {
  CLEAR_TASK_STATE: 'CLEAR_TASK_STATE',

  GET_TASK_LIST: 'GET_TASK_LIST',
  GET_TASK_LIST_SUCCESS: 'GET_TASK_LIST_SUCCESS',
  GET_TASK_LIST_FAILURE: 'GET_TASK_LIST_FAILURE',
}

export default TaskTypes
